### ISSUE TITLE
Strange data transformation of MiniTest::Assertions.diff (tested on OSX)

### ISSUE THREAD

**Issue by phuesler** [seattlerb/minitest#494]
````ruby
expected = "FMOD::Thread::callback (in CrashUnityTest_4_6_IL2CPP_64bit_slow_and_safe) + 489640"
actual = "0x00000001007e0844"

assert_equal expected, actual
````
````
  1) Failure:
test_unity_il2cpp_test_subprograms_empty_cache(TestAtosl) [/Users/phuesler/work/wooga/atosl/test/integration_test.rb:68]:
--- expected
+++ actual
@@ -1 +1 @@
-"FMOD::Thread::callback (in CrashUnityTest_4_6_IL2CPP_64bit_slow_and_safe) + 489640"
+"0xXXXXXX
````

Setting `MiniTest::Assertions.diff = nil` fixes the problem.

**Comment by zenspider** [comment]
Can I see the test code? And if you've overridden `mu_pp` and/or `mu_pp_for_diff`, I'd like the code for that too.

By default, `mu_pp_for_diff` does an inspect with some simple substitutions:

```ruby
    def mu_pp_for_diff obj
      mu_pp(obj).gsub(/\\n/, "\n").gsub(/:0x[a-fA-F0-9]{4,}/m, ":0xXXXXXX")
    end
```

(`mu_pp` just calls inspect by default).

This implies to me that you've got two different types (with two different inspects) and the equality method (`==`) isn't checking the class of the two (perhaps because they're considered equivalent types). But something else could be going on too.

You might be interested in `make_my_diffs_pretty!`.

**Comment by phuesler** [comment]
test code: https://github.com/wooga/atosl/blob/master/test/integration_test.rb#L64
test helper: (that turns off the diff): https://github.com/wooga/atosl/blob/master/test/test_helper.rb#L55

In case you want to run the tests of this project:

* I created a [test release](https://github.com/wooga/atosl/releases/tag/2.0alpha) of the binary that you can copy into the project so that you don't have to deal with the build process
* It will download around 200 MB of test fixtures into test/fixtures

**Comment by zenspider** [comment]
Gotcha... I have a better understanding now that I've read the test. You just want to turn off the hex munging, yes?

```ruby
    def mu_pp_for_diff obj
      mu_pp(obj).gsub(/\\n/, "\n")
    end
```

Pop that into your Test subclass to override anywhere you don't want the munging and you should get the benefit of both worlds.

**Comment by phuesler** [comment]
got it, I will give that a try. Thank you for your help.

**Comment by zenspider** [comment]
How's it going?

**Comment by phuesler** [comment]
works like a charm. Thx

**Comment by zenspider** [comment]
If you're good, please close.
