### ISSUE TITLE
minitest spec can't run tests in alphabetical order since version 5.3.4

### ISSUE THREAD

**Issue by gregkare** [seattlerb/minitest#514]
We have a project that _really_ needs specs to run in fixed order, we run into an issue where minitest included in Ruby 2.1 and gem versions 5.3.4 and above run specs in random order even when calling `i_suck_and_my_tests_are_order_dependent!`. The version that ships with Ruby 2.2 doesn't have that problem, same as versions 5.3.3 and below.

Here's a gist: https://gist.github.com/gregkare/a88bacf666eff0e84066

**Comment by blowmage** [comment]
Test classes are [randomized](https://github.com/seattlerb/minitest/commit/8bd2249c31e10cfece3a9ae7068e60adc98108ea) as of 5.3.4. The sorting is for test methods in the test class. I don't think there is an option to control the order of how test classes are run. When you split your tests across multiple `describe` blocks they will be in different test classes.

**Comment by zenspider** [comment]
Correct. As you can see in your gist, the test _methods_ are still running in alphabetical order, but the test _classes_ are not.

Test order dependencies are **bugs** in your tests that can and will lead to errors in production code. You should seriously consider fixing your tests so that each one is order independent. Full randomization with 100% success should be your goal. If you have a lot of tests, this can be a daunting task, but seattlerb/minitest-bisect can absolutely help with that.

If you're for some reason absolutely 100% dead-set on keeping your test order dependency (errors), you'll have to monkey patch `Minitest.__run`.

**Comment by skddc** [comment]
> Test order dependencies are bugs in your tests that can and will lead to errors in production code. You should seriously consider fixing your tests so that each one is order independent.

This is actually not true for our suite. In normal tests I would agree, but we're (mis)using minitest in order to integration-test API servers against [a protocol spec](https://remotestorage.io/) from the outside, and for that we need to e.g. first PUT something until we can test GETs and DELETEs.

**Comment by skddc** [comment]
... what I'm saying is, if your library prevents valid use cases from being implemented for the sake of a pseudo-religious argument coming from a single perspective, then maybe that's not as good a thing as you think it is. ;)

In my opinion, code itself should try not to have too many opinions. Humans know best about business domain/logic and requirements.

**Comment by blowmage** [comment]
Either you 1) are misusing minitest or 2) it is a valid use case. I don't see how it can be both. Either way, I don't think name calling is the right way to go to get the change you are seeking.

The test class' `test_order` is meant to control the order the test methods are run in the test class, not the  order of the test classes. That said, you can get the behavior you are looking for by putting the following in your test helper:

```ruby
module Minitest
  def self.__run reporter, options
    suites = Runnable.runnables
    parallel, other = suites.partition { |s| s.test_order == :parallel }
    random, sorted  = other.partition  { |s| s.test_order == :random }

    sorted.map { |suite| suite.run reporter, options } +
      random.shuffle.map   { |suite| suite.run reporter, options } +
      parallel.shuffle.map { |suite| suite.run reporter, options }
  end
end
```

Or, you can move all of your GETs and DELETEs into well named methods and call them all in order in a single test.

**Comment by zenspider** [comment]
Well, at least we agree that you're misusing minitest.

If you can't run every single **test** method individually (ie, via `-n`) then you have broken tests. Period. 

Refactoring and making it so each test declares all the setup it needs is the correct way to test.

As said before, if you insist on keeping test order dependency errors, then you'll have to monkeypatch Minitest to get your way. Yes, **you have to do a bad thing to support a bad thing**, and it may break in the future.

**Comment by skddc** [comment]
Sorry, it was not my intention to call names! I'm not a native speaker, so it might have come across more confrontational than it should have and the "(mis)using" was more meant as "using in a creative way for something it's not used for in the overwhelming amount of cases".

Still, the latest comment again shows why I called it a pseudo-religious argument, as the poster just takes the fact that our tests are broken (with exclamation marks and period) for granted, no matter what, because of their perspective and never having run into a situation that's completely different than what they base their <del>belief</del> opinion on. Let's just agree to disagree on if this is a valid use case and if we do *bad things™* and all our code is an error-prone bugfest. There's room for all opinions there I think, and we don't have a problem with using a method called `i_suck_and_my_tests_are_order_dependent!` to begin with.

It works fine in Ruby 2.2 and I really do appreciate you documenting how to get the behaviour in future versions, @blowmage!

**Comment by zenspider** [comment]
> Still, the latest comment again shows why I called it a pseudo-religious argument, as the poster just takes the fact that our tests are broken (with exclamation marks and period) for granted

I see no such thing.

> because of their perspective and never having run into a situation that's completely different than what they base their belief opinion on

Don't make assumptions about people critiquing your approach. Maybe we _have_ run into this situation before and from experience know that there are better ways to do things that have fewer long term maintenance and debugging consequences.

This isn't our first rodeo. Personally, I've been doing TDD since 1995... Yes, that's before the XP book was published.

Closing, since we just seem to be talking past each other.
