### ISSUE TITLE
Attempting to install MiniTest with MediumSecurity or higher fails.

### ISSUE THREAD

**Issue by jdickey** [seattlerb/minitest#558]
```
$ gem install -P MediumSecurity minitest
ERROR:  While executing gem ... (Gem::Security::Exception)
    root cert /CN=ryand-ruby/DC=zenspider/DC=com is not trusted
```

Signed Gems with trustable certificates would be Helpful.

**Comment by zenspider** [comment]
Apparently I created my cert back in 2009 and newer generated certs have more info in them. I've plonked around a bit and got a gem I can install via HighSecurity, but it requires that I type my passphrase on every gem build. Until I can get either a passwordless cert built or ssh-agent answering for me, I'm not willing to add that level of disruption for every release.

@drbrain might have some suggestions on what I can do to generate a cert that'll make both you and me happy.

Regardless, the **huge** downside is that no matter what I do, it'll invalidate _**every**_ gem I've ever released under the previous cert (read: the high hundreds), which is a huge bummer.

**Comment by jdickey** [comment]
Yes, that *is* a *huge* fscking downside. The juxtaposition of barn doors, horses, and strategic nuclear weapons comes to mind.

We're starting to get some pressure from (potential/actual) stakeholders to have a transparent, "sensibly modern" security stance with respect to the code that we develop and what we use to develop it with. It seems to me that we've got pieces of a decent set of protocols put together after a couple of *spectacular* public security failures, but actually *using* it has fallen prey to the "it's too much work, let's wait/oh, it's even more work now; let's wait some more" circlejerk. This isn't a problem with any one developer or package, it's an *ecosystem* problem. Maybe the Chinese hackers will get around to Rubygems.org and it'll be 2013 all over again, but more visible this time. That could either kill us (the community) or force the beancounters into supporting the moon-shot effort to fix things the way we know how but haven't been able to afford to do. &lt;/rant&gt;

Thanks for at least replying, and I apologise for mouthing off on Twitter. :disappointed:

**Comment by drbrain** [comment]
Do you get this message after `gem cert -a`?

The design of signed gems at present is terribly labor intensive.

**Comment by zenspider** [comment]
@drbrain not sure if that was to me or OP. I regenerated a cert, was forced to put a passphrase on it (seemingly w/o ssh-agent support?), added the cert to my trust list, and now when I package I'm forced to enter the passphrase (despite having global ssh-agent set up).

Is there a way to generate either a passphraseless cert OR to get it hooked up to work with ssh-agent? I don't mind doing the former manually if I have to.

**Comment by drbrain** [comment]
My comment was to @jdickey, he has to mark the cert as trusted in order for RubyGems to not complain.

@zenspider The password on your cert is through OpenSSL instead of ssh, so it doesn't integrate with Keychain or ssh-agent.  If you strip the password from the .pem RubyGems won't care, it creates one with a password by default for security reasons.

RubyGems could be updated to look for a password from disk, but stripping the password will be sufficient.

**Comment by zenspider** [comment]
@jdickey take a look at http://www.zenspider.com/~ryan/security.txt

Don't run it blindly, tho I've run it several times on my system now. That's the gist of the security model for rubygems. In my specific case, there's some added complexity to deal with my certificate provider not being in the major root chains. The script uses `security` to add the certificate root for cacert.org to the keychain, but `security` assumes/imples you're running on OSX. I don't know the equivalent cmds for linux/windows/whatever.

The first curl also has `-k` to disable cert verification, since cacert uses cacert there is a chicken&egg problem going on.

I was able to use this script and now `-P MediumSecurity` works fine.

**Comment by jdickey** [comment]
@zenspider Great! Many thanks!

**Comment by zenspider** [comment]
Let me know if that works for you. If you're on a different system, please let me know what you find out for adding that cert to your root chain and I'll update my script accordingly.

**Comment by jdickey** [comment]
@drbrain My notes don't have anything about `gem cert -a`, so I'm quite willing to believe I was doing it wrong.

@zenspider I've been pulled off onto other, more loudly complained-about things for the last few days — we're feeling rather like four guys on the pitch against Chelsea at the moment — but people have been told that I'll make progress against this this week. :mask:

**Comment by zenspider** [comment]
Anything? Please close if you think your issues have been addressed.

**Comment by jdickey** [comment]
@zenspider That [script](http://www.zenspider.com/~ryan/security.txt) you posted was indeed very helpful. I've had other fires to deal with in the interim, and I apologise for letting this go on so long. I'm satisfied. Part of me says this is a festering sore *much* bigger than MiniTest, but other folks with better understanding of How Things Work seem to agree but have their own higher priorities.

Thanks again for your help!
