### ISSUE TITLE
Please make a tag for each release

### ISSUE THREAD

**Issue by gfx** [seattlerb/minitest#606]
It's easy. Just add `require "bundler/gem_tasks"` in Rakefile, which defines a task `release`. And then run `rake release`, which does release engineering including make a tag and push it to the remote.

**Comment by zamith** [comment]
@gfx It's not that easy, because Minitest's primary version management system is not git, nor is the primary hosting of it GitHub, if I'm not mistaken. This has also been discussed in #557, but we came to no conclusion.

I do think this would be useful, but it is not a must have and ultimately the decision is up to @zenspider.

**Comment by gfx** [comment]
Oh, I see. I wish a good conclusion be made.
