### ISSUE TITLE
Exclude test by file

### ISSUE THREAD

**Issue by utilum** [seattlerb/minitest#609]
This is the remaining part of #519.

Negative filtering should be able to reject entire files (which will require being able to map files to tests?).

https://github.com/utilum/minitest/commit/9c01f7afbbcc47ffcfe63de1f595a2857abf2ea8 answers this, but has compatibility issues as it uses #source_location.

I'm trying to find a way around that.

**Comment by zenspider** [comment]
I'm not against using `source_location`... just need to come up with a reasonable policy. Dropping 1.8 is **not** unreasonable.

**Comment by zenspider** [comment]
P.S. I'm going to release your other patch today.

**Comment by utilum** [comment]
Cool.

**Comment by zenspider** [comment]
OK. I'm working on figuring out what I want to do about this feature. Basically involves officially declaring that 1.8 support is dropped. (which is fine--just need to figure out _how_ and _when_).

**Comment by utilum** [comment]
Announce it in Paris. I'm sure that Paris.rb would be delighted to host the announcement.

**Comment by utilum** [comment]
@zenspider I see that 1.8 (++) will be dropped with version 6. Still... I think I see how this can be included before dropping support. Proposed behavior would pend on support for `source_location`, if supported works as is, else... warns and ignores option ? Raises invalid option ?

**Comment by zenspider** [comment]
I think I'm over the backwards compatibility thing...

I don't remember the full context around this (3 years!)... but since `minitest-sprint` uses `path_expander`, you have the ability to exclude files on the command-line. Is that all that's needed?

Unfortunately, for things like #519, excluding files is not sufficient. They have to load in order to get the same sized suite so `rand`/`shuffle` has the same effect. I've been thinking that for minitest_bisect that the run should post the entire collection of tests in the correct order at the very start, and then each subsequent run (regardless of exclusion) can `&` against that list to maintain the same order... that involves changing some of the protocol and needs to be worked out more, but it seems like a sound idea.

**Comment by zenspider** [comment]
I think this is closable? Please re-open if you think otherwise.
