### ISSUE TITLE
Add colour output for minitest

### ISSUE THREAD

**Issue by harsh183** [seattlerb/minitest#641]
So while everyone uses minitest reporters for the red/green colour output I suggest that this should be default as it makes output more readable and there is little to lose by adding it. Perhaps there can be a flag to mark if the user does not want a colour output (for those who may not want it)

**Comment by zamith** [comment]
I think the idea of minitest is to be a strong core with all (and only) the necessary things to run your tests. It also aims at being extensible, so that other libraries can build on top of it to provide new functionality, such as the minitest reporters.

If you take this into account, I do not believe color output fits into the core.

**Comment by zenspider** [comment]
Agreed. It takes ~2 lines (1 dependency & 1 require) to add color to your test runs versus adding however many lines of code and asking people to opt out via more mechanisms. This doesn't fit the minitest way.

P.S. I highly recommend something like minitest-rg over minitest-reporters. Fewer moving parts (58 loc & 56 flog vs 1279 loc & 1520 flog).
