### ISSUE TITLE
Unit Test inheritance

### ISSUE THREAD

**Issue by andrew-aladev** [seattlerb/minitest#644]
Hello. I have a very strange problem.

```
require 'minitest'

class A < Minitest::Unit::TestCase
  CONSTANT = 0
  def test_a
    puts "ololo - " + self.class::CONSTANT.to_s
    assert self.class::CONSTANT == 1, "constant is " + self.class::CONSTANT.to_s
  end
end

class B < A
  CONSTANT = 1
  Minitest.run
end
```

It returns:
> ololo - 1
ololo - 0

Why? It looks like a bug.

**Comment by andrew-aladev** [comment]
```
def self.inherited klass # :nodoc:
  self.runnables << klass
  super
end
```

Here we have both `A` and `B`. Why?

```
def self.methods_matching re
  public_instance_methods(true).grep(re).map(&:to_s)
end
```
We have `public_instance_methods(include_super=true)`. It will provide all methods of A and B that you can imagine. What is a point of running `A.new.test_a` and `B.new.test_a`?

**Comment by zenspider** [comment]
Sorry, but it's absolutely intentional and important to being able to refactor tests into abstract test types. In your scenario, both `A` and `B` are definitely considered `runnables`.

You can either use `skip` or redesign your class layout. This will not change in minitest.

Please let me know if I missed or misunderstood anything.

**Comment by andrew-aladev** [comment]
Skipping single class is not a solution.

```
require 'minitest'
class A < Minitest::Unit::TestCase
end
class B < A
end
class C < B
end

puts A.runnables.inspect
puts B.runnables.inspect
puts C.runnables.inspect
```

> [Minitest::Test, Minitest::Unit::TestCase, A, B, C]
[Minitest::Test, Minitest::Unit::TestCase, A, B, C]
[Minitest::Test, Minitest::Unit::TestCase, A, B, C]

WAT? `B.runnables` equals `A`, `B`, `C`.

```
require 'minitest'
class A < Minitest::Unit::TestCase
  @runnables = [self]
  class << self
    attr_accessor :runnables
    def inherited klass
      klass.runnables = [klass]
    end
  end
end
class B < A
end
class C < B
end

puts A.runnables.inspect
puts B.runnables.inspect
puts C.runnables.inspect
```

> [A]
[B]
[C]

But `Minitest.run` wont work. It just do not care about each class `runnables`. It uses global `Runnables.runnables`. So minitest will run all public instance methods of any inheritor of `Runnable` and`inheritor.runnables` has no sense.

**Comment by andrew-aladev** [comment]
```
require 'minitest'

module Minitest
  class << self
    alias_method :original_process_args, :process_args
    def process_args args = []
      options = original_process_args
      options[:runnables] = args[:runnables]
      options
    end

    def __run reporter, options
      runnables = options[:runnables] || Runnable.runnables
      suites = runnables.shuffle
      parallel, serial = suites.partition { |s| s.test_order == :parallel }
      serial.map { |suite| suite.run reporter, options } +
        parallel.map { |suite| suite.run reporter, options }
    end
  end
end

class A < Minitest::Unit::TestCase
  CONSTANT = 0
  def test_a
    assert self.class::CONSTANT == 1, "constant is " + self.class::CONSTANT.to_s
  end
end

class B < A
  CONSTANT = 1
end

class C < A
  CONSTANT = 2
end

Minitest.run :runnables => [C, B]
```

> 2 runs, 2 assertions, 1 failures, 0 errors, 0 skips

This is what I've expected. Can we have `runnables` option for `Minitest.run` in upstream? Should I provide a pull request?

**Comment by zenspider** [comment]
> WAT? B.runnables equals A, B, C.

It is. Because `B.runnables` is `Runnable.runnables` which returns a shared class variable that all `Runnable` subclasses use. This is intentional and the way that test discovery works in minitest.

> But I am sure you won't like this solution.

You're right. I don't. But not for reasons you might think. You have yet to explain the _*WHY*_ of your use case. The current use case is clear, as I stated above. Until you do, the best I can do is guess as to your reasoning. I simply don't do that.

> It works with inherited. Can we let user to define its own accumulator and pass it to Minitest somehow?

No. As I said above:

> This will not change in minitest.

Is there some reason _why_ you want to do this? So far you've shown me overly abstract examples of failing tests that aren't of any value to begin with (eg testing against constants in the test classes themselves). What are you actually trying to do? You've thrown a lot of words and code at me but communicated little as to your needs or reasoning.

**Comment by zenspider** [comment]
Also, as a total aside:

+ `MiniTest::Unit::TestCase` became `Minitest::Test`3 years ago.
+ Use `assert_equal` whenever possible.
+ Use string interpolation (eg `"constant is #{self.class::CONSTANT}"`), although you don't need to if you use `assert_equal` in this case.

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
No response. I can't work without feedback. Closing.
