### ISSUE TITLE
Please retain assert_send

### ISSUE THREAD

**Issue by rab** [seattlerb/minitest#668]
When updating gems, I was surprised by a huge number of deprecation warnings in the rspec output—all stemming from use of `assert_send` which is apparently sitting on the deprecation block.

I tend to use `assert_send` mainly for predicate methods to get a much more useful default message on failure that a simple `assert` gives.

```ruby
assert_send [2, :odd?]
```

produces a much nicer message:

```
  1) Failure:
TestAssertSend#test_with_assert_send [test_assert_send.rb:4]:
Expected 2.odd?(*[]) to return true.
```

 than the "equivalent"

```ruby
assert 2.odd?
```

that just gives the cryptic:

```
  2) Failure:
TestAssertSend#test_with_assert [test_assert_send.rb:8]:
Expected false to be truthy.
```

which doesn't help anyone.

Of course, the more explicit `assert 2.odd?, "Why wasn't 2 odd?"` can replace this, but that would need to be made literally hundreds of times (in this application's code) and take a little bit more brain power away from the real task of getting the system to work.

FYI, the deprecation was added in seattlerb/minitest@f95ef007ec64d956d88fedc37fd2ed7e106b777e

**Comment by nateberkopec** [comment]
Why not just use `assert_predicate`?

The error message is even nicer: `Expected 2 to be odd?`

**Comment by zenspider** [comment]
I agree with @nateberkopec. This is literally the first case of finding `assert_send` actually being used in the wild in 10 years of its being (and much longer before that with test/unit). I've never seen it used, never found a utility in it, never thought it made sense, and don't see value in it.

As @nateberkopec pointed out, `assert_predicate` has even better error messages than `assert_send`. Switching to `assert_predicate` should be fairly trivial with a proper text editor or even `sed` or `ruby -pi`. Otherwise you can put this in your tests:

```ruby
def assert_send ary
  assert_predicate(*ary)
end
```

**Comment by rab** [comment]
OK, so I can resolve nearly 100% of the occurrences of `assert_send` by changing to `assert_predicate`, `assert_operator`, or `assert_respond_to`. (and for my complement `refute_send` to the `refute_…` versions)

It does concern me a bit that the docs for `assert_predicate` say:

> This is really meant for specs and is front-ended by `#assert_operator`:

which sounds like it isn't _really_ guaranteed to stay a public method.

There are still a few places where the method being called isn't really a predicate and `assert_operator` isn't quite right either, but that's really just a place that can't rely on the default message.
