### ISSUE TITLE
Wanting more ways to work with order dependent tests

### ISSUE THREAD

**Issue by natethinks** [seattlerb/minitest#681]
Bringing this up again because minitest seems really useful but all I do is selenium automation. The test I am building right now is literally going through an online signup flow page by page which definitely NEEDS to be order dependent. You can't signup in any other order than what the user flow dictates.

At the very least it would be very helpful to have an official way of doing before_tests(). In a lot of cases selenium testing isn't so much order dependent as much as it needs setup at the beginning before tests are run (declare browsers, set cookies)

**Comment by nateberkopec** [comment]
This change has been rejected before. See #400.

**Comment by natethinks** [comment]
Guess I'll look for other tools then, thanks!

**Comment by zenspider** [comment]
What does renaming a method have to do with `before_tests()` ?

**Comment by zenspider** [comment]
BTW, nobody is forcing you to use that method. This is all it does:

```ruby
def self.test_order
  :alpha
end
```

and you're welcome to do that instead.

**Comment by natethinks** [comment]
This might have been better broken up into other issues. Don't really care if the name changes (changed the issue title obviously) Mainly just wish we had a setup and teardown that would only run once.

**Comment by zenspider** [comment]
once _only_ or once per class or?

**Comment by natethinks** [comment]
I could find a lot of use for both of those, but i'd settle for either

**Comment by zenspider** [comment]
@natethinks once only for setup is just a method with cache, then use it (and you don't even need a method, just code initializing something at the top level will do it too).

Once only for cleanup is `Minitest.after_run`.

Once only per class is overriding `run` and calling super within, like so:

https://gist.github.com/zenspider/6e160c35e366250e7a693286a11f18b5

(note that it is using extend because you're overriding the class method run, not instance method run)

**Comment by natethinks** [comment]
Brilliant, thanks for the help! That covers everything I was looking for

**Comment by zenspider** [comment]
Closing
