### ISSUE TITLE
cert expired

### ISSUE THREAD

**Issue by mikeforbes** [seattlerb/minitest#710]
```
# /bin/bash -l -c "gem install minitest -P HighSecurity"
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=ryand-ruby/DC=zenspider/DC=com not valid after 2017-09-26 01:57:35 UTC
```
😞

**Comment by zenspider** [comment]
uuuuuuggggghhhhhh

**Comment by zenspider** [comment]
Should I just stop signing my gems?? It forces people to suspect the validity of stable gems. I shouldn't have to do empty releases JUST to update the signing of the gem.

I'm asking you because I do this mechanically, and not for any other reason but to provide it. I don't think about this stuff in terms of security at all (doesn't come naturally to me).

**Comment by mikeforbes** [comment]
I have to admit I don't know much about how involved the signing is. I do think about security stuff and an unsigned gem does make me squirm, but there's a lot of them out there.

**Comment by zenspider** [comment]
AFAIK, later rubygems auto-update my public key as needed, so all I need to do is re-release. I _usually_ do that often enough it shouldn't matter. Either way, I think this has long been fixed. Closing.
