### ISSUE TITLE
What is the best way to prevent plugins from loading?

### ISSUE THREAD

**Issue by tenderlove** [seattlerb/minitest#725]
I have Rails installed, but I'm not working on a Rails project.  Since Minitest picks up plugins from any gem installed on my system, it picks up the Rails plugin and gives me Rails colorized output along with incorrect instructions:

![output](https://dl.dropboxusercontent.com/s%2F8dtpw4uau3ihvmy%2Faoc%2520%25E2%2580%2594%2520-bash%2520%25E2%2580%2594%2520159%25C3%259732%25202017-12-04%252011-01-01.png)

So far, the solutions I've tried:

1. Always use Bundler and never install Rails system-wide
2. Use GEM_HOME and GEM_PATH to point somewhere else
3. Write some code that prevents all plugins from getting loaded

The first solution doesn't work well for me because a) I don't always want to use Bundler, and b) since I do testing with Rails I need to install it system-wide so that the `rails` commandline tool is available.

The second solution doesn't work well because I have to remember to do it, and I may not have gem installed in the target path (which means I may as well be using Bundler at this point).

The third solution seems to work, but I need to make sure to copy the snippet of code everywhere.

Personally, I don't want my project to use *any* plugins automatically, I would rather explicitly activate the plugins (I don't understand the benefit of automatically loaded plugins).  But given the current circumstances, what do you recommend I do to prevent this?

**Comment by nateberkopec** [comment]
> I don't understand the benefit of automatically loaded plugins

We do this in `sentry-raven` but the context there is a lot different - it's a commercial product and people expect it to "just work". But to me the Minitest Way is to be more explicit and clear about what's going on.

The best argument I can think of for plugins being automatic is that Minitest is a pretty modular ecosystem that expects you to use lots of plugins ("No I will not put that in Minitest core, please use a plugin!"). So if we use plugins a lot, they should be easy to use.

**Comment by zenspider** [comment]
@tenderlove the problem is less about minitest loading plugins (it's _always_ done this and rarely has it been a problem) than it is having poorly behaving plugins installed. Rails in this case assumes that if it *can* load, then you *must* be doing rails development, rather than having a flag or ENV that they use to activate (which they could easily do via the `rails test` path). I warned you about this a LONG time ago and you let it go in as-is and now you're feeling the repercussions.

There are other minitest plugin interactions that cause known problems. See #707 showing a problem between minitest-reporters (which has a long history of being problematic) and minitest-parallel_fork.

The ability to `gem install minitest-xxx` and then easily opt-in via some flag (`--xxx`) has long been considered a feature. If it then needs to be explicitly required you lose this ease-of-use. 

Some things just make total sense being explicit require (eg `minitest-around` or `minitest-vcr`), but some aren't things you'd necessarily WANT to stick in your code (eg `--server <port>`, or `--debugger`). What do you suggest for these cases?

**Comment by tenderlove** [comment]
> The ability to gem install minitest-xxx and then easily opt-in via some flag (--xxx) has long been considered a feature.

Why not use the `--xxx` flag to know what to load rather than implicitly loading files from random gems?

Regardless of Rails' behavior, say a dep of a dep has a minitest plugin that I don't really care about.  How do I prevent it from running?  Is the onus for opting out of a plugin supposed to be put on every plugin author?  Why is this an opt-out system and not an opt-in system?

In this case, I have a bad-apple plugin and no escape.

**Comment by tenderlove** [comment]
> I warned you about this a LONG time ago and you let it go in as-is and now you're feeling the repercussions.

Warned me, but didn't file a bug or comment on [the PR](https://github.com/rails/rails/pull/29572) which I [think you knew about](https://github.com/rails/rails/issues/29469#issuecomment-310921763). 😜

**Comment by tenderlove** [comment]
I'd personally settle for a `--disable-plugins` command line option, such that you'd have to explicitly require the plugin.  I think this means we'd have to do argument processing multiple times because plugins are allowed to do argument processing (we'd have to scan ARGV for this special option before sending ARGV off to plugins to be scanned again).

Anyway, I think there will always be "bad actor" plugins (like Rails in this case, which we will fix) and I'd like an escape valve of some sort.  I will try to think of a non-gross way to implement this and send a PR, but I wanted to file a ticket in case anyone else runs in to this issue.  😀

**Comment by zenspider** [comment]
We might be mixing terms/goals here at this point. This question is a bit confusing to me:

> Is the onus for opting out of a plugin supposed to be put on every plugin author? Why is this an opt-out system and not an opt-in system?

The onus on the plugin author is to write it to be opt-IN. Minitest _trusts_ that the plugins will be well behaved. It can't/won't sandbox or provide other more convoluted mechanisms to ensure it plays nicely (everything is a lambda?, maybe? I dunno). The problem is that rails and minitest-reporters are enacting changes that you did **not** opt IN to.

Am I misunderstanding your terminology? (This might be one of those "If I'm looking at the clock **or** I am the clock" things I get tripped up on)

The flow is:

```
autorun
  run
    load_plugins
    process_args (which calls through to plugin_*_options)
    init_plugins
```

The intent is that `load_plugins` discovers and requires, `process_args` provides the user an opt-in mechanism, and `init_plugins` acts on those opt-ins. If code runs inside of `plugin_*_init` that isn't conditionalized, **then it is a bad actor**.

So having `--disable-plugins` is a bit of a bootstrapping issue. I've drafted this up:

```diff
diff -r old/lib/minitest.rb new/lib/minitest.rb
--- old/lib/minitest.rb
+++ new/lib/minitest.rb
@@ -118,7 +118,7 @@
   #                   klass.new(runnable_method).run
 
   def self.run args = []
-    self.load_plugins
+    self.load_plugins unless args.delete("--no-plugins") || ENV["MT_NO_PLUGINS"]
 
     options = process_args args
 
@@ -175,6 +175,8 @@
         exit
       end
 
+      opts.on "--no-plugins", "Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS)."
+
       desc = "Sets random seed. Also via env. Eg: SEED=n rake"
       opts.on "-s", "--seed SEED", Integer, desc do |m|
         options[:seed] = m.to_i
```

**Comment by zenspider** [comment]
@jeremyevans ping

**Comment by zenspider** [comment]
For the record, here is what rails should **NOT** be doing at all without conditionals.

## Requiring into rails:

https://github.com/rails/rails/blob/master/railties/lib/minitest/rails_plugin.rb#L3-L5

## Infecting the reporters configuration:

https://github.com/rails/rails/blob/master/railties/lib/minitest/rails_plugin.rb#L47-L49

and probably this too, changing the order of the plugins (not sure why):

https://github.com/rails/rails/blob/master/railties/lib/minitest/rails_plugin.rb#L16

**Comment by zenspider** [comment]
> Warned me, but didn't file a bug or comment on the PR which I think you knew about.

This doesn't account for all the OTHER related issues I did interact on. OR my IRC activity. OR OR OR... https://github.com/rails/rails/pull/19571 has 106 comments on it alone. Eventually it felt like an uphill battle that I couldn't fight even with daily face-to-face with you. 🤷‍♀️ I can only do so much.

**Comment by jeremyevans** [comment]
I'd be happy with some way to disable the loading of plugins.  I think it would be best to require all plugins be loaded explicitly, but even just the ability to disabling implicit loading when it does cause a problem would be a very useful addition.

**Comment by zenspider** [comment]
I just submitted my code above... Thanks everyone.
