### ISSUE TITLE
Optional plan support (assert the expected number of tests)

### ISSUE THREAD

**Issue by chocolateboy** [seattlerb/minitest#754]
Many test frameworks allow a "plan" to be specified e.g.:

* [AVA](https://github.com/avajs/ava#assertion-planning)
* [QUnit](http://api.qunitjs.com/assert/expect)
* [Tape](https://github.com/substack/tape#tplann)
* [Test::More](https://perldoc.perl.org/Test/More.html#I-love-it-when-a-plan-comes-together)

This asserts the expected number of tests as a kind of additional test e.g.:

```ruby
plan 3
assert foo
assert bar
``` 

    Error: expected 3 assertions, got: 2

It could help to catch cases like [this](https://github.com/bbatsov/powerpack/issues/34) where tests are accidentally disabled. It can also be useful (in conjunction with a `done` or `end` method) when testing asynchronous code.

I guess this can be done manually (e.g. via [`total_count`](https://github.com/kern/minitest-reporters/blob/3479b15e95de701f8d9766ae864fa15446da2aaf/lib/minitest/minitest_reporter_plugin.rb#L35) as mentioned [here](https://github.com/seattlerb/minitest/issues/629)), but it looks like that method was never made public. In addition, support for an explicit plan would allow seamless integration with `skip` e.g.:

```ruby
plan 3
assert foo
assert bar
skip 1, "baz is unimplemented"
``` 

    OK

**Comment by zenspider** [comment]
I certainly do this within minitest's tests, but that's to test the internals to an extent. I'm not convinced as to their utility as they break across many tests because I add an internal assertion to something and the counts are wrong.

I'm not sure I'm bought into this feature request... what would it really get you, besides constantly having to update it whenever you add/remove/modify a test?

**Comment by zenspider** [comment]
No response. Closing.
