### ISSUE TITLE
assert_raises takes String msg only

### ISSUE THREAD

**Issue by svoop** [seattlerb/minitest#755]
Experimenting with custom assertions which use `assert_raises`, I stumbled across the following line:

https://github.com/seattlerb/minitest/blob/1f2b1328f286967926a381d7a34e0eadead0722d/lib/minitest/assertions.rb#L322

```ruby
msg = "#{exp.pop}.\n" if String === exp.last
```

In other parts, `msg` may be a Proc which is [e.g. called here](https://github.com/seattlerb/minitest/blob/1f2b1328f286967926a381d7a34e0eadead0722d/lib/minitest/assertions.rb#L138).

Is there a reason for this inconsistency?

If not, adding the following should help:

```ruby
msg = "#{exp.pop.call}\n" if Proc === exp.last
```

**Comment by zenspider** [comment]
Custom assertions which want to defer their message generation? Can you show me an example?

**Comment by svoop** [comment]
@zenspider It's more than a year and even looking back at the commits I made around when I asked this, I can't remember what use case I was thinking off. Guess we can close this. Thanks!

**Comment by zenspider** [comment]
That's on me. Sorry for the slow response. I'm only just starting to catch up on things.

As far as assert_raises goes... `message` (or any lambda) is really only meant to defer the calculation of strings until after an actual failure has occurred (ie, why do all the interpolation if it is gonna pass?). Being able to pass down a `message` proc is certainly a possibility, but unless you're writing compound assertions, probably isn't necessary for normal use.

Happy to take a PR that allows for both tho. I realize that isn't likely since you just closed.

**Comment by svoop** [comment]
@zenspider No biggie. I've switched to MiniTest as my test suite of choice, therefore I'll dive into the source every now and then. In case I run into this use case again, I'd be happy to do a PR. However, since I cannot recall it right now, it makes little sense to implement it "for fun and clutter". :smile:

**Comment by zenspider** [comment]
totally. thank you and, again, sorry for dropping the ball on this one.
