### ISSUE TITLE
BacktraceFilter returns nil

### ISSUE THREAD

**Issue by lzap** [seattlerb/minitest#837]
Hey, I am digging in the codebase but I am unable to find why we see exception "NoMethodError: undefined method `split' for nil:NilClass" on this line:

    assert_equal nil, nil

There appear to be somehow complex filtering of stacktrace, but it looks like it returns `nil` for the object on `split` is called in our environment:

            where = Minitest.filter_backtrace(caller).first
            where = where.split(/:in /, 2).first # clean up noise

The test in question is: https://ci.theforeman.org/job/test_plugin_matrix/1742/database=postgresql,ruby=2.5,slave=fast/console

I am going to fix our test to avoid those `nil` values, it was a copy and paste error. But creating this ticket in case you can spot what's actually wrong.

**Comment by deivid-rodriguez** [comment]
In case it helps, I found this when running [mobile-fu](https://github.com/benlangfeld/mobile-fu) to package the library for debian, and figured it was an incompatibility with Rails backtrace cleaner. I [workarounded it like this](https://salsa.debian.org/ruby-team/ruby-mobile-fu/-/commit/5d9c0526612c7f8b661f264e4ba1bc2b61a0a55e), since the `BACKTRACE` variable is used internally by Rails to avoid backtrace cleaning.

**Comment by zenspider** [comment]
If this is a test in rails, then it's probably not my backtrace_filter. If so, please file with rails.

**Comment by lzap** [comment]
I am not sure I understand the problem and I would be able to articulate in RoR. Thanks for help!

**Comment by zenspider** [comment]
I got a fix into rails AND added some defensive coding to minitest to prevent this in the future. Just released too!
