### ISSUE TITLE
assert failure backtrace is stripped too much

### ISSUE THREAD

**Issue by serguei-at-bemaximus** [seattlerb/minitest#849]
Hello,

My test fails like this:
```
F

Failure:
TheControllersTest#test_the_happy_path [/Users/me/workspace/someproject/test/test_helper.rb:25]:
Expected: 1
  Actual: 0
```

Now, if the test_helper method is called multiple times throughout `test_the_happy_path`, It would be very helpful to see more of the stacktrace. How to achieve this? I'm noticing throughout the source code of minitest a whole lot of `Minitest::filter_backtrace(...).first`. why `.first`? Isn't that too much stripping when you're using test helpers?

**Comment by zenspider** [comment]
I can't tell from this report as there's not enough information to go on...

What is the hypothetical code in test_helper.rb:25?

**Comment by serguei-at-bemaximus** [comment]
well, it's stuff like

```
 22     def sign_in(email)
 23       post session_url, params: { login_attempt: { email: email, password: password } }
 24       assert_equal 200, status
 25       assert_equal '/session', path
 26           
```

and `sign_in` is called in various tests as various api calls are made from various users. So if a `test_happy_path` scenario has a few sign_in invocations, I don't know which one failed with only the top line of the stack trace.

**Comment by zenspider** [comment]
Name it `assert_signin` and the backtrace will be on the caller.

**Comment by zenspider** [comment]
And to answer your other question... in the case of a failure (not an error (an uncaught exception)), we _want_ to report the call site of the failing assertion and that's why it uses `.first`. It isn't minitest's job to know the difference between a helper method, or a regular test method, or an inherited test method, etc... so it filters and then uses `.first` to find the call to the assertion that fails...

So, if you name your helper to be a compound assertion (which based on the above is exactly what that is), then its caller of `assert_signin` will be the reported assertion that failed.

**Comment by zenspider** [comment]
P.S. Welcome to github and welcome to minitest.

**Comment by serguei-at-bemaximus** [comment]
huh, gonna try that assert_ prefix. Didn't know that's the convention. Will report if that does it.

**Comment by zenspider** [comment]
also works with refute/must/wont methods.

**Comment by serguei-at-bemaximus** [comment]
I see. So I gave it a try. And it did in fact replace the line with the line of the "caller" (the test, rather than assert/helper):
```
Failure:
TheControllersTest#test_the_happy_path [test/controllers/the_controllers_test.rb:10]:
```

Tbh, why not both or some other treatment.
In the meantime, I opened the gem and changed the location method on `Assertion` class:
```
 881     def location
 882       #last_before_assertion = ""
 883       #self.backtrace.reverse_each do |s|
 884       #  break if s =~ /in .(assert|refute|flunk|pass|fail|raise|must|wont)/
 885       #  last_before_assertion = s
 886       #end
 887       #last_before_assertion.sub(/:in .*$/, "")
 888       self.backtrace.join("\n") #personal edit
 889     end 
```

Now I'm happy. When an assertion fails I get the whole stack trace.

I get that maybe it's nice to keep the output of a failure terse, but I think there's a good case to be made for printing a whole stack trace.

**Comment by zenspider** [comment]
The whole stack trace is not helpful in the context of a failure... it certainly is in an error, but in a failure, the assertion that fails is the thing you want to be pointed at.

I do not see the value in printing multiple lines for a failure. If anything, it will be confusing. If you want to make an actual case for it, I'll hear you out, but "I'm happy" isn't compelling.

**Comment by serguei-at-bemaximus** [comment]
I think I see where you're coming from. The connotation of `assert_` is that it's a leaf-node, low-level thing that you shouldn't dig into to see where inside it failed. I can see how for the out-of-the-box `assert_` methods that come with minitest, that's true.

I guess my question to you is: If you were to adopt my goal, to have an elaborate `test_` scenario that has nested building blocks such as `sign_in`, `onboard`, `configure_preferences`, etc. (multi-request workflows), how would you go about it? It's natural for me to express this using methods calling methods, then stacktrace informing where in that tree an error occurred, but I'm open to suggestions.

**Comment by zenspider** [comment]
I'm not sure I fully understand what you're describing in your last paragraph... it almost seems like a separate issue entirely... 

That said, I wouldn't go about it. "elaborate scenario" and "nested building blocks" are yellow/red flags for me. Of course your tests have to set things up and do things to work. But once something fails, that's it. Stop. Report where the problem was when it happened and leave it at that. If you want something more complex than that, minitest (as-is) will not meet your needs.

**Comment by zenspider** [comment]
I haven't heard back in 2 weeks... assuming this is settled.
